### ISSUE TITLE
Why not the TypeAheadComponent define the state?

### ISSUE THREAD

**Issue by lshoo** [yysun/apprun-apress-book#3]
I look the chapter_05/typeahead/TypeAheadComponent  don't define the state properties, but had define view and update.
Why not define the state, and How to know the state has any properties?

**Comment by yysun** [comment]
It extends the super class, the Component class that has a default state, which has the value of null.

**Comment by lshoo** [comment]
but I don't known what type of state, what attribute of state

**Comment by yysun** [comment]
The update creates the state where the state object properties are changed dynamically.
